[package]
name = "bot"
version = "0.1.0"
edition = "2021"

[dependencies]
# From Workspace
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
config = { workspace = true }
validator = { workspace = true }
reqwest = { workspace = true }

# Only for this
tokio = "1.44.2"
serenity = { version = "0.12.4", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
shuttle-runtime = "0.53.0"
shuttle-serenity = "0.53.0"